Cleanup juju and storage modules
Also removes dangling F_OUT env var and executes plugins
as process rather than in local context (which was meant
to be fixed in prev commit.

diff --git a/plugins/juju/01juju b/plugins/juju/01juju
--- a/plugins/juju/01juju
+++ b/plugins/juju/01juju
@@ -1,71 +1,82 @@
 #!/bin/bash -u
 # This plugin displays information about Juju.
 
-if [ -d "var/log/juju" ]; then
-    echo -e "juju:"
+unit_in_array ()
+{
+    unit="$1"
+    shift
+    echo $@| egrep -q "\s?${unit}\s?"
+}
 
-    readarray -t ps_units<<<"`grep unit- ps| sed -r 's,.+unit-([[:alnum:]\-]+-[[:digit:]]+).*,\1,g;t;d'| sort -u`"
-    readarray -t log_units<<<"`find var/log/juju -name unit-\*.log| sed -r 's,.+unit-([[:alnum:]\-]+-[[:digit:]]+).*.log.*,\1,g;t;d'| sort -u`"
-    combined_units=( `echo ${ps_units[@]} ${log_units[@]}| tr -s ' ' '\n'| sort -u` )
+data_source_dir=var/log/juju
+if ! [ -d "$data_source_dir" ]; then
+    echo "$data_source_dir not found - skipping juju info"
+    exit 0
+fi
 
-    readarray -t ps_machines<<<"`egrep machine-\* ps| sed -r 's,.+machine-([[:digit:]]+).*,\1,g;t;d'| sort -u`"
-    readarray -t log_machines<<<"`find var/log/juju -name machine-\*| sed -r 's,.+machine-([[:digit:]]+).*.log.*,\1,g;t;d'| sort -u`"
+echo "juju:"
 
-    declare -a juju_machine_running=()
-    declare -a juju_machine_stopped=()
-    
-    for machine in ${log_machines[@]}; do
-        agent_conf=var/lib/juju/agents/machine-${machine}/agent.conf
-        version=unknown
-        if [ -r "$agent_conf" ]; then
-            version=`sed -r 's/upgradedToVersion:\s+(.+)/\1/g;t;d' $agent_conf`
-        fi
-        if unit_in_array $machine ${ps_machines[@]}; then
-            juju_machine_running+=( "${machine} (version=$version)\n" )
-        else
-            juju_machine_stopped+=( "${machine}\n" )
-        fi
-    done
+readarray -t ps_units<<<"`grep unit- ps| sed -r 's,.+unit-([[:alnum:]\-]+-[[:digit:]]+).*,\1,g;t;d'| sort -u`"
+readarray -t log_units<<<"`find var/log/juju -name unit-\*.log| sed -r 's,.+unit-([[:alnum:]\-]+-[[:digit:]]+).*.log.*,\1,g;t;d'| sort -u`"
+combined_units=( `echo ${ps_units[@]} ${log_units[@]}| tr -s ' ' '\n'| sort -u` )
 
-    declare -a juju_unit_local=()
-    declare -a juju_unit_local_not_running=()
-    declare -a juju_unit_nonlocal=()
-    
-    for unit in ${combined_units[@]}; do
-        if unit_in_array $unit ${log_units[@]}; then
-            if unit_in_array $unit ${ps_units[@]}; then
-                juju_unit_local+=( "${unit}\n" )
-            else
-                juju_unit_local_not_running+=( "${unit}\n" )
-            fi
-        else
-            juju_unit_nonlocal+=( "${unit}\n" )
-        fi
-    done
+readarray -t ps_machines<<<"`egrep machine-\* ps| sed -r 's,.+machine-([[:digit:]]+).*,\1,g;t;d'| sort -u`"
+readarray -t log_machines<<<"`find var/log/juju -name machine-\*| sed -r 's,.+machine-([[:digit:]]+).*.log.*,\1,g;t;d'| sort -u`"
 
-    (("${#ps_machines[@]}")) && [ -n "${ps_machines[0]}" ] || ps_machines+=( null )
-    echo -e "  machines:"
-    echo -e "    running:"
-    echo -e ${juju_machine_running[@]}| sort -u| xargs -l -I{} echo "    ${INDENT_STR}{}"
-    if ((${#juju_machine_stopped[@]})) && [ -n "${juju_machine_stopped[0]}" ]; then
-        echo -e "    stopped:"
-        echo -e ${juju_machine_stopped[@]}| sort -u| xargs -l -I{} echo "    ${INDENT_STR}{}"
+declare -a juju_machine_running=()
+declare -a juju_machine_stopped=()
+
+for machine in ${log_machines[@]}; do
+    agent_conf=var/lib/juju/agents/machine-${machine}/agent.conf
+    version=unknown
+    if [ -r "$agent_conf" ]; then
+        version=`sed -r 's/upgradedToVersion:\s+(.+)/\1/g;t;d' $agent_conf`
     fi
-
-    echo -e "  units:"
-    if (("${#ps_units[@]}"==0)) || [ -z "${ps_units[0]}" ]; then
-        echo -e "    any:"
-        echo "      ${INDENT_STR}null"
+    if unit_in_array $machine ${ps_machines[@]}; then
+        juju_machine_running+=( "${machine} (version=$version)\n" )
     else
-        echo -e "    running:"
-        echo -e ${juju_unit_local[@]}| sort -u| xargs -l -I{} echo "    ${INDENT_STR}{}"
-        echo -e "    stopped:"
-        echo -e ${juju_unit_local_not_running[@]}| sort -u| xargs -l -I{} echo "    ${INDENT_STR}{}"
-        echo -e "    non-local (e.g. lxd):"
-        if (("${#juju_unit_nonlocal[@]}"==0)) || [ -z "${juju_unit_nonlocal[0]}" ]; then
-            juju_unit_nonlocal=( null )
-        fi
-        echo -e ${juju_unit_nonlocal[@]}| sort -u| xargs -l -I{} echo "    ${INDENT_STR}{}"
+        juju_machine_stopped+=( "${machine}\n" )
     fi
+done
+
+declare -a juju_unit_local=()
+declare -a juju_unit_local_not_running=()
+declare -a juju_unit_nonlocal=()
+
+for unit in ${combined_units[@]}; do
+    if unit_in_array $unit ${log_units[@]}; then
+        if unit_in_array $unit ${ps_units[@]}; then
+            juju_unit_local+=( "${unit}\n" )
+        else
+            juju_unit_local_not_running+=( "${unit}\n" )
+        fi
+    else
+        juju_unit_nonlocal+=( "${unit}\n" )
+    fi
+done
+
+(("${#ps_machines[@]}")) && [ -n "${ps_machines[0]}" ] || ps_machines+=( null )
+echo -e "  machines:"
+echo -e "    running:"
+echo -e ${juju_machine_running[@]}| sort -u| xargs -l -I{} echo "    ${INDENT_STR}{}"
+if ((${#juju_machine_stopped[@]})) && [ -n "${juju_machine_stopped[0]}" ]; then
+    echo -e "    stopped:"
+    echo -e ${juju_machine_stopped[@]}| sort -u| xargs -l -I{} echo "    ${INDENT_STR}{}"
+fi
+
+echo -e "  units:"
+if (("${#ps_units[@]}"==0)) || [ -z "${ps_units[0]}" ]; then
+    echo -e "    any:"
+    echo "      ${INDENT_STR}null"
+else
+    echo -e "    running:"
+    echo -e ${juju_unit_local[@]}| sort -u| xargs -l -I{} echo "    ${INDENT_STR}{}"
+    echo -e "    stopped:"
+    echo -e ${juju_unit_local_not_running[@]}| sort -u| xargs -l -I{} echo "    ${INDENT_STR}{}"
+    echo -e "    non-local (e.g. lxd):"
+    if (("${#juju_unit_nonlocal[@]}"==0)) || [ -z "${juju_unit_nonlocal[0]}" ]; then
+        juju_unit_nonlocal=( null )
+    fi
+    echo -e ${juju_unit_nonlocal[@]}| sort -u| xargs -l -I{} echo "    ${INDENT_STR}{}"
 fi
 
diff --git a/plugins/storage/01ceph b/plugins/storage/01ceph
--- a/plugins/storage/01ceph
+++ b/plugins/storage/01ceph
@@ -1,33 +1,46 @@
 #!/bin/bash -u
 # This plugin displays information about Ceph.
 
-echo -e "ceph:"
-
+declare -a output=()
 services=(
     ceph-osd
     ceph-mon
     ceph-mgr
     radosgw
 )
-if [ -r "ps" ]; then
-    hash=`md5sum $F_OUT`
-    ( for svc in ${services[@]}; do
-        out="`sed -r \"s/.*(${svc}[[:alnum:]\-]*)\s+.+/\1/g;t;d\" ps| sort| uniq| sed -r 's/^\s+/  /g'`"
-        id="`sed -r \"s/.*(${svc}[[:alnum:]\-]*)\s+.+--id\s+([[:digit:]]+)\s+.+/\2/g;t;d\" ps| tr -s '\n' ','| sort| sed -r -e 's/^\s+/  /g' -e 's/,$//g'`"
-        [ -z "$out" ] && continue
-        for osd_id in `echo $id| tr ',' ' '`;do
-            echo -n "${INDENT_STR}ceph-osd (id=$osd_id)"
-            if [ -e "sos_commands/ceph/ceph-volume_lvm_list" ]; then
-                offset=`egrep -n "osd id\s+$osd_id\$" sos_commands/ceph/ceph-volume_lvm_list| cut -f1 -d:`
+
+data_source=ps
+if ! [ -r "$data_source" ]; then
+    echo "  $data_source not found - skipping ceph service detection"
+    exit 0
+fi
+
+echo "ceph:"
+
+for svc in ${services[@]}; do
+    exists="`sed -r \"s/.*(${svc}[[:alnum:]\-]*)\s+.+/\1/g;t;d\" $data_source| sort| uniq| sed -r 's/^\s+/  /g'`"
+    [ -z "$exists" ] && continue
+
+    ids="`sed -r \"s/.*(${svc}[[:alnum:]\-]*)\s+.+--id\s+([[:digit:]]+)\s+.+/\2/g;t;d\" $data_source| tr -s '\n' ','| sort| sed -r -e 's/^\s+/  /g' -e 's/,$//g'`"
+    for osd_id in `echo $ids| tr ',' ' '`;do
+        out_str="ceph-osd (id=$osd_id)"
+        if [ -s "sos_commands/ceph/ceph-volume_lvm_list" ]; then
+            offset=`egrep -n "osd id\s+$osd_id\$" sos_commands/ceph/ceph-volume_lvm_list| cut -f1 -d:`
+            if [ -n "$offset" ]; then
                 osd_fsid=`tail -n+$offset sos_commands/ceph/ceph-volume_lvm_list| grep "osd fsid"| head -n 1| sed -r 's/.+\s+([[:alnum:]]+)/\1/g'`
                 osd_device=`tail -n+$offset sos_commands/ceph/ceph-volume_lvm_list| grep "devices"| head -n 1| sed -r 's/.+\s+([[:alnum:]\/]+)/\1/g'`
-                echo -n " (fsid=$osd_fsid) (device=$osd_device)"
+                out_str="$out_str (fsid=$osd_fsid) (device=$osd_device)"
             fi
-            echo ""
-        done
-    done )
-    [ "$hash" = "`md5sum $F_OUT`" ] && echo "${INDENT_STR}null"
+        fi
+        output+=( "$out_str" )
+    done
+done
+
+if ((${#output[@]})); then
+    for line in "${output[@]}"; do
+        echo "${INDENT_STR}$line"
+    done
 else
-    echo "  ps not found - skipping ceph service detection"
+    echo "${INDENT_STR}null"
 fi
 
diff --git a/plugins/storage/02bcache b/plugins/storage/02bcache
--- a/plugins/storage/02bcache
+++ b/plugins/storage/02bcache
@@ -1,14 +1,23 @@
 #!/bin/bash -u
 # This plugin module displays information about bcache.
 
+declare -a output=()
+
+data_source=sos_commands/block/ls_-lanR_.sys.block
+if ! [ -r "$data_source" ]; then
+    echo "  $data_source not found - skipping bcache detection"
+    exit 0
+fi
+
 echo "bcache-info:"
-readarray -t bcacheinfo<<<"`grep . sos_commands/block/ls_-lanR_.sys.block| egrep 'bcache|nvme'| sed -r 's/.+[[:digit:]\:]+\s+([[:alnum:]]+)\s+.+/\1/g'`"
-((${#bcacheinfo[@]})) && [ -n "${bcacheinfo[0]}" ] || bcacheinfo=( "null" )
+
+readarray -t bcacheinfo<<<"`grep . $data_source| egrep 'bcache|nvme'| sed -r 's/.+[[:digit:]\:]+\s+([[:alnum:]]+)\s+.+/\1/g'`"
 block_root=sos_commands/block/udevadm_info_.dev.
 for bcache_name in ${bcacheinfo[@]}; do
     udev_info=${block_root}$bcache_name
+    out_str="$bcache_name"
     if [[ $bcache_name = "null" ]]; then
-        echo $bcache_name && break
+        break
     fi
     backing_dev=
     if [ -e "$udev_info" ]; then
@@ -17,21 +26,28 @@ for bcache_name in ${bcacheinfo[@]}; do
         backing_dev=${f##*.}
     fi
 
-    entry=$bcache_name
-    if [ -e "${block_root}$bcache_name" ]; then
-        entry="/dev/$bcache_name"
+     if [ -e "${block_root}$bcache_name" ]; then
+        out_str="$out_str /dev/$bcache_name"
     fi
 
     if [ -e "${block_root}$bcache_name" ]; then
         dname=`grep ' disk/by-dname' ${block_root}$bcache_name| sed -r 's,.+/(.+),\1,g'`
         if [ -n "$dname" ]; then
-            entry="$entry (dname=$dname)"
+            out_str="$out_str (dname=$dname)"
         fi
     fi
     if [ -n "$backing_dev" ]; then
-        entry="$entry (backing=/dev/$backing_dev)"
+        out_str="$out_str (backing=/dev/$backing_dev)"
     fi
 
-    echo $entry
-done| xargs -l -I{} echo "${INDENT_STR}{}"
+    output+=( "$out_str" )
+done
+
+if ((${#output[@]})); then
+    for line in "${output[@]}"; do
+        echo "${INDENT_STR}$line"
+    done
+else
+    echo "${INDENT_STR}null"
+fi
 
