Report low count of high-order mem zones
Also reports compaction errors if high-order zones
are not available.

diff --git a/plugins/kernel/01kernel b/plugins/kernel/01kernel
--- a/plugins/kernel/01kernel
+++ b/plugins/kernel/01kernel
@@ -1,7 +1,7 @@
 #!/bin/bash -u
 # This plugin displays information about the kernel.
 
-echo -e "kernel:"
+echo "kernel:"
 
 path=${DATA_ROOT}proc/cmdline
 if [ -e "$path" ]; then
@@ -16,13 +16,60 @@ fi
 #    cat $data_source | egrep "zone\s+Normal,"| sed -r 's/\s+/ /g'
 #fi
 
-fail_count=`awk '$1=="compact_fail" {print $2}' ${DATA_ROOT}proc/vmstat`
-success_count=`awk '$1=="compact_success" {print $2}' ${DATA_ROOT}proc/vmstat`
-if ((success_count)); then
-    pcent=$((fail_count/(success_count/100)))
-    if ((pcent>10)); then
-        echo "${INDENT_STR}WARNING: memory compaction failures > 10% of successes ($pcent%)"
+echo "${INDENT_STR}memory:"
+
+
+INDENT_STR="    $INDENT_STR"
+
+check_mallocinfo ()
+{
+    local node="$1"
+    local verbose=${2:-0}
+    local tally=0
+    local high_order_seq=0
+    local stop=false
+
+    ((verbose)) && echo "${sub_indent_str}zones:"
+    for zone in {10..0}; do
+        free=`awk '$4=="Normal"' ${DATA_ROOT}proc/buddyinfo| grep "Node $node,"| sed -r 's/\s+/ /g'| cut -d ' ' -f $((5+$zone))`
+        ((verbose)) && echo "  ${sub_indent_str}$zone: $free"
+        ((free)) || ((tally+=$zone))
+        ((free)) && stop=true
+        $stop || ((high_order_seq++))
+    done
+    ((tally>50)) && ((high_order_seq>1)) && return 1
+    ((high_order_seq>5)) && return 1
+    return 0
+}
+readarray -t nodes<<<"`sed -rn 's/Node\s+([0-9]+).+/\1/p' ${DATA_ROOT}proc/buddyinfo| sort -u`"
+zone_issue_found=false
+
+sub_indent_str="  $INDENT_STR"
+for node in ${nodes[@]}; do
+    check_mallocinfo $node
+    if (($?)); then
+        echo "      node$node:"
+        zone_issue_found=true
+        echo "${sub_indent_str}WARNING: node $node has limited high order memory - check ${DATA_ROOT}proc/buddyinfo"
+        check_mallocinfo $node 1
     fi
+done
+
+# We only report on compaction errors if there is a shortage of high-order zones
+if $zone_issue_found; then
+    fail_count=`awk '$1=="compact_fail" {print $2}' ${DATA_ROOT}proc/vmstat`
+    success_count=`awk '$1=="compact_success" {print $2}' ${DATA_ROOT}proc/vmstat`
+    # we use an arbitrary threshold of 10k to suggest that a lot of compaction has
+    # occured but noting that this is a rolling counter and is not necessarily
+    # representative of current state.
+    if ((success_count>10000)); then
+        pcent=$((fail_count/(success_count/100)))
+        if ((pcent>10)); then
+            echo "${INDENT_STR}WARNING: compaction failures are at $pcent% of successes (see ${DATA_ROOT}proc/vmstat)"
+        fi
+    fi
+else
+    echo "${INDENT_STR}zones checked, no issues found"
 fi
 
 echo -e "systemd:"
